apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-nodejs-quay
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-application-deployment
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/example-app-nodejs/.kustomize/quay
    repoURL: 'https://github.com/pkstaz/demo-application-deployment.git'
    targetRevision: develop

    kustomize: {}