{{- range untilStep (int .Values.FirstUser) (int .Values.LastUser) (int .Values.Interval) }}
{{ $n := . }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "user{{$n}}"
  namespace: openshift-gitops
spec: {}
{{- end }}