{{- range untilStep (int .Values.FirstUser) (int .Values.LastUser) (int .Values.Interval) }}
{{ $n := . }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: user{{$n}}
users:
  - user{{$n}}
{{- end }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: opentlc-mgr
users:
  - opentlc-mgr